// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' ;
import 'package:flutter/foundation.dart';
import 'package:get/get.dart';

Future<void>main() async{
  await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform).then((FirebaseApp value) => Get.put(()),
  );
  }

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(

///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa4Y2KqM3Pv-Y97Y9BZvGbe3GvTp1xlRU',
    appId: '1:81473550052:web:564439caf3d93a42565ef1',
    messagingSenderId: '81473550052',
    projectId: 'dentalexpert-62520',
    authDomain: 'dentalexpert-62520.firebaseapp.com',
    storageBucket: 'dentalexpert-62520.appspot.com',
    measurementId: 'G-J5BK9T1MSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkJx1s134cXUdNPI5V1hjaEqI4mcCJni4',
    appId: '1:81473550052:android:6376765590361251565ef1',
    messagingSenderId: '81473550052',
    projectId: 'dentalexpert-62520',
    storageBucket: 'dentalexpert-62520.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBgfVrxhSkd6t0r6FM3N4IonTTprX_s1Q',
    appId: '1:81473550052:ios:cb0f12e2b9fef7aa565ef1',
    messagingSenderId: '81473550052',
    projectId: 'dentalexpert-62520',
    storageBucket: 'dentalexpert-62520.appspot.com',
    iosBundleId: 'com.example.search',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBgfVrxhSkd6t0r6FM3N4IonTTprX_s1Q',
    appId: '1:81473550052:ios:cb0f12e2b9fef7aa565ef1',
    messagingSenderId: '81473550052',
    projectId: 'dentalexpert-62520',
    storageBucket: 'dentalexpert-62520.appspot.com',
    iosBundleId: 'com.example.search',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa4Y2KqM3Pv-Y97Y9BZvGbe3GvTp1xlRU',
    appId: '1:81473550052:web:fbf11d350daf6f0c565ef1',
    messagingSenderId: '81473550052',
    projectId: 'dentalexpert-62520',
    authDomain: 'dentalexpert-62520.firebaseapp.com',
    storageBucket: 'dentalexpert-62520.appspot.com',
    measurementId: 'G-BR3Q9DZS5F',
  );

}